version: "3"
services:
  mysqldb:
    image: mysql
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: trivia
      MYSQL_DATABASE: trivia_db
  trivia-api:
    build: .
    environment:
      DB_HOST: mysqldb
      DB_USER: root
      DB_PASSWORD: trivia
      DB_NAME: trivia_db
    depends_on:
      - mysqldb
    ports:
      - "8200:8080"

volumes:
  mysql_volume: {}